// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvfvaukjytvdyvdzmona.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2ZnZhdWtqeXR2ZHl2ZHptb25hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNTI5NjMsImV4cCI6MjA3MzkyODk2M30.GMz_Z0IavhFyfQ0d2Urpj4m5bDb9gjPLZcBxtfchWU0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});